"use client"
import "@repo/ui/globals.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "~/components/Header";
const queryClient = new QueryClient();

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased  bg-gradient-to-b from-[#FFF5E1] to-[#FFD8B1]  w-full min-h-screen `}
      >
        <Header />
        <QueryClientProvider client={queryClient}>
          {children}
        </QueryClientProvider>
      </body>
    </html>
  );
}
